# Build runtime image
FROM dev.docker.registry:5000/vendor/mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
EXPOSE 5002
ENV ASPNETCORE_URLS http://*:5002
COPY ./out/ .
ENTRYPOINT ["dotnet", "psw.itms.api.dll"]